/* ==================== بداية وحدة إدارة الموظفين ====================
 * حفظ وتحرير واستيراد وعرض بيانات الموظفين.
 * ==================== نهاية وصف وحدة إدارة الموظفين ==================== */
function employeeRecords() { return safeJson(appStorage.getItem(EMPLOYEES_KEY) || "[]", []); }
function saveEmployeeRecords(records) { appStorage.setItem(EMPLOYEES_KEY, JSON.stringify(records.slice(0, 1000))); }
function employeeDepartments() { return safeJson(appStorage.getItem(EMPLOYEE_DEPARTMENTS_KEY) || "[]", []); }
function renderEmployeeDepartments() { const list = $("#employeeDepartmentOptions"); if (list) list.innerHTML = employeeDepartments().map((x) => `<option value="${escapeHtml(x)}"></option>`).join(""); }
function employeeNetSalary(employee) { const base = Number(employee.salary || 0);
  const insurance = Number(employee.insurance || 0); const day = Number(employee.workDays || 0) ? base / Number(employee.workDays) : 0; return Math.max(0, base - insurance - Number(employee.deductions || 0) - day * Number(employee.leaveDays || 0)); }
function resetEmployeeForm() { ["employeeEditingId","employeeName","employeeCode","employeeJob","employeePhone","employeeHireDate","employeeYear","employeeDepartment","employeeWorkDays","employeeWorkHours","employeeSalary","employeeInsurance","employeeDeductions","employeeLeaveDays","employeeNotes"].forEach((id) => { const el = $("#" + id); if (el) el.value = ""; }); $("#employeeWorkDays").value = "26"; $("#employeeWorkHours").value = "8"; $("#employeeSubmit").textContent = "إضافة الموظف"; }
function renderEmployeeManager() {
  const box = $("#employeeList"); if (!box) return;
  renderEmployeeDepartments();
  const query = normalize($("#employeeManagerSearch")?.value || "");
  const records = employeeRecords();
  const rows = records.filter((e) => !query || normalize(`${e.name} ${e.code} ${e.job} ${e.department} ${e.year}`).includes(query)).slice(0, 200);
  box.innerHTML = rows.length ? rows.map((e) => `<div class="employee-row"><div><strong>${escapeHtml(e.name)} · ${escapeHtml(e.code || "—")}</strong><small>${escapeHtml(e.job || "—")} · ${escapeHtml(e.phone || "—")} · السنة ${escapeHtml(e.year || "—")} · القسم ${escapeHtml(e.department || "—")} · ${escapeHtml(e.workDays || 0)} يوم · ${escapeHtml(e.workHours || 0)} ساعة يوميًا</small><small>المرتب ${money(e.salary)} · الخصومات ${money(e.deductions)} · الإجازات ${escapeHtml(e.leaveDays || 0)} · الصافي ${money(employeeNetSalary(e))}</small><small>${escapeHtml(e.notes || "")}</small></div><div class="user-row-actions"><button type="button" class="btn ghost small" data-employee-edit="${escapeHtml(String(e.id))}">تعديل</button><button type="button" class="btn danger small" data-employee-delete="${escapeHtml(String(e.id))}">حذف</button></div></div>`).join("") : '<div class="empty-row">لا توجد بيانات موظفين</div>';
  box.querySelectorAll("[data-employee-edit]").forEach((b) => b.addEventListener("click", () => editEmployee(b.dataset.employeeEdit)));
  box.querySelectorAll("[data-employee-delete]").forEach((b) => b.addEventListener("click", () => deleteEmployee(b.dataset.employeeDelete)));
}
async function openEmployeeManager() { if (!requireFeatureAccess("employeeManagement", "إدارة الموظفين للمطورين فقط")) return; if (!(await requireAdminAreaPassword("إدارة الموظفين"))) return; closeAccountMenu(); resetEmployeeForm(); renderEmployeeManager(); bumpModalZIndex($("#employeeManagerModal")); $("#employeeManagerModal")?.classList.remove("hidden"); }
function closeEmployeeManager() { $("#employeeManagerModal")?.classList.add("hidden"); }
function editEmployee(id) { const e = employeeRecords().find((x) => String(x.id) === String(id)); if (!e) return; $("#employeeEditingId").value = e.id; $("#employeeName").value = e.name || ""; $("#employeeCode").value = e.code || ""; $("#employeeJob").value = e.job || ""; $("#employeePhone").value = e.phone || ""; $("#employeeHireDate").value = e.hireDate || ""; $("#employeeYear").value = e.year || ""; $("#employeeDepartment").value = e.department || ""; $("#employeeWorkDays").value = e.workDays || ""; $("#employeeWorkHours").value = e.workHours || ""; $("#employeeSalary").value = e.salary || ""; $("#employeeInsurance").value = e.insurance || ""; $("#employeeStatus").value = e.status || "active"; $("#employeeDeductions").value = e.deductions || ""; $("#employeeLeaveDays").value = e.leaveDays || ""; $("#employeeNotes").value = e.notes || ""; $("#employeeSubmit").textContent = "حفظ التعديل"; }
async function deleteEmployee(id) { if (!(await openConfirmModal("هل تريد حذف سجل الموظف؟"))) return; saveEmployeeRecords(employeeRecords().filter((e) => String(e.id) !== String(id))); renderEmployeeManager(); toast("تم حذف الموظف"); }
function submitEmployee(event) { event.preventDefault(); if (!requireFeatureAccess("employeeManagement", "إدارة الموظفين للمطورين فقط")) return; const id = $("#employeeEditingId").value || makeId("employee"); const name = $("#employeeName").value.trim(); if (!name) { $("#employeeError").textContent = "اكتب اسم الموظف"; return; } const department = $("#employeeDepartment").value.trim(); const departments = new Set(employeeDepartments()); if (department) departments.add(department); appStorage.setItem(EMPLOYEE_DEPARTMENTS_KEY, JSON.stringify([...departments])); const record = { id, name, code: $("#employeeCode").value.trim() || makeId("EMP"), job: $("#employeeJob").value.trim(), phone: $("#employeePhone").value.trim(), hireDate: $("#employeeHireDate").value, year: $("#employeeYear").value.trim(), department, workDays: Number($("#employeeWorkDays").value) || 0, workHours: Number($("#employeeWorkHours").value) || 0, salary: Number($("#employeeSalary").value) || 0, insurance: Number($("#employeeInsurance").value) || 0, deductions: Number($("#employeeDeductions").value) || 0, leaveDays: Number($("#employeeLeaveDays").value) || 0, status: $("#employeeStatus").value || "active", notes: $("#employeeNotes").value.trim(), updatedAt: new Date().toISOString() }; const records = employeeRecords(); const index = records.findIndex((e) => e.id === id); if (index >= 0) records[index] = record; else records.unshift(record); saveEmployeeRecords(records); recordAdminLog(index >= 0 ? "تعديل موظف" : "إضافة موظف", name); resetEmployeeForm(); renderEmployeeManager(); toast("تم حفظ بيانات الموظف وحساب صافي المرتب"); }
function exportEmployees() { if (!requireFeatureAccess("employeeManagement", "تصدير الموظفين للمطورين فقط")) return; openExportImportModal("employees"); }
async function importEmployees(file) { try { const data = JSON.parse(await file.text()); const records = Array.isArray(data) ? data : data.employees; if (!Array.isArray(records)) throw Error(); saveEmployeeRecords(records); if (Array.isArray(data.departments)) appStorage.setItem(EMPLOYEE_DEPARTMENTS_KEY, JSON.stringify(data.departments)); renderEmployeeManager(); toast("تم استيراد بيانات الموظفين"); } catch (e) { toast("ملف الموظفين غير صحيح"); } }

/* ==================== نهاية وحدة إدارة الموظفين ==================== */
